src/SchoolOfRock.Web/Models/BaseCreateOrEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolOfRock.Web.Models
{
    public class BaseCreateOrEditModel<TModel> where TModel : class
    {
        public BaseCreateOrEditModel() { }
        public BaseCreateOrEditModel(TModel _model)
        {
            model = _model;
        }

        public TModel model { get; set; }
    }
}

src/SchoolOfRock.Web/Models/TraningCreateOrEditModel.cs
using SchoolOfRock.Core.Models;
using SchoolOfRock.Core.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolOfRock.Web.Models
{
    public class TraningCreateOrEditModel : BaseCreateOrEditModel<Traning>
    {
        public TraningCreateOrEditModel()
        {

        }

        public TraningCreateOrEditModel(Traning _model, UnitOfWork _unit) : base(_model)
        {

        }
    }

    public class ScheduleSettingModel
    {
        public ScheduleSettingModel()
        {
            ScheduleList = new List<ScheduleItem>();
        }

        public List<ScheduleItem> ScheduleList { get; set; }
        public int TraningId { get; set; }
    }
}

src/SchoolOfRock.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SchoolOfRock.Core.Models;
using SchoolOfRock.Core.Repository;
using SchoolOfRock.Web.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Reflection;
using SchoolOfRock.Core.Tools;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SchoolOfRock.Web.Controllers
{
    public class BaseController<TModel, TPK> : Controller where TModel : class
    {
        protected ApplicationDBContext context { get; set; }
        protected UnitOfWork unit { get; set; }
        protected BaseRepository<TModel, TPK> repository { get; set; }
        protected ModelLogger logger { get; set; }

        public BaseController(ApplicationDBContext _context)
        {
            context = _context;
            unit = new UnitOfWork(context);
            logger = new ModelLogger(context);
        }

        [HttpGet]
        public virtual IActionResult Index()
        {
            var result = repository.GetAll();
            return View(result);
        }

        [HttpGet]
        public virtual IActionResult Detail(TPK Id)
        {
            var result = repository.GetById(Id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        [HttpGet]
        public virtual IActionResult CreateOrEdit(TPK Id, int logId = -1)
        {
            var model = repository.GetById(Id) ?? Activator.CreateInstance(typeof(TModel));
            var result = new BaseCreateOrEditModel<TModel>(model as TModel);
            ViewBag.Messages = logger.GetByOpration(logId);
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual IActionResult CreateOrEdit(BaseCreateOrEditModel<TModel> _formResult)
        {
            if (ModelState.IsValid)
            {
                TModel model = _formResult.model;
                var result = repository.IsExist(model) ? repository.Update(model) : repository.Add(model);
                model = result.Object;
                unit.Commit();
                return RedirectToAction("CreateOrEdit", new { Id = model.GetType().GetProperty("Id").GetValue(model), logId = logger.Add(new List<LogMessage>() { result.Message }) });
            }
            return BadRequest(GetModelStateErrors(ModelState));
        }


        public virtual List<string> GetModelStateErrors(ModelStateDictionary modelState)
        {
            List<string> result = new List<string>();
            foreach (var itemVal in modelState.Values)
            {
                foreach (var itemError in itemVal.Errors)
                {
                    result.Add(itemError.ErrorMessage);
                }
            }
            return result;
        }
    }
}

src/SchoolOfRock.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SchoolOfRock.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/SchoolOfRock.Web/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SchoolOfRock.Core.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SchoolOfRock.Web.Controllers
{
    public class ScheduleController : BaseController<ScheduleItem,int>
    {
        public ScheduleController(ApplicationDBContext _context) : base(_context)
        {
            repository = unit.Schedules;
        }
    }
}

src/SchoolOfRock.Web/Controllers/TraningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SchoolOfRock.Core.Models;
using SchoolOfRock.Web.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SchoolOfRock.Web.Controllers
{
    public class TraningController : BaseController<Traning, int>
    {
        public TraningController(ApplicationDBContext _context) : base(_context)
        {
            repository = unit.Tranings;
        }

        [HttpGet]
        public IActionResult ScheduleEdit(int Id, int logId = -1)
        {
            var model = unit.Schedules.Find(m => m.TraningId == Id)?.ToList() ?? new List<ScheduleItem>();
            var result = new ScheduleSettingModel()
            {
                ScheduleList = model,
                TraningId = Id
            };
            ViewBag.Messages = logger.GetByOpration(logId);
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ScheduleEdit(ScheduleSettingModel _formResult)
        {
            if (ModelState.IsValid)
            {
                var Messages = new List<LogMessage>();
                foreach (var item in _formResult.ScheduleList)
                {
                    Messages.Add( unit.Schedules.IsExist(item.Id) 
                        ? unit.Schedules.Update(item).Message 
                        : unit.Schedules.Add(item).Message );
                }
                unit.Commit();
                logger.Add(Messages);
                return RedirectToAction("Index");
            }
            return BadRequest(GetModelStateErrors(ModelState));
        }

        [HttpPost]
        public IActionResult GetScheduleForm(int index, int traningId)
        {
            var traning = repository.GetById(traningId);
            if (traning == null)
            {
                return BadRequest("Ошибка передачи данных");
            }
            var result = new ScheduleSettingModel();
            for (int i = 0; i < index; i++)
            {
                result.ScheduleList.Add(new ScheduleItem());
            }
            result.ScheduleList.Add(new ScheduleItem()
            {
                TraningId = traningId,
                Traning = traning
            });
            ViewBag.Index = index;
            return View("_ScheduleEditItem", result);
        }
    }
}

src/SchoolOfRock.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/SchoolOfRock.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/SchoolOfRock.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

src/SchoolOfRock.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolOfRock.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ТУТ БУДЕТ ЛОГО</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Рабочий стол</a></li>
                    <li><a asp-area="" asp-controller="Traning" asp-action="Index">Курсы</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - SchoolOfRock.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/SchoolOfRock.Web/Views/Traning/CreateOrEdit.cshtml
@model SchoolOfRock.Web.Models.TraningCreateOrEditModel
@{ 
    Layout = "_Layout";
    ViewData["Title"] = "Форма создания/редактирования курса";
}

<h2>@ViewData["Title"]</h2>
<hr />
<form asp-action="CreateOrEdit" enctype="multipart/form-data">
    <div class="form-horizontal">
        @{
            if (Model.model.Id > 0)
            {
                <input asp-for="model.Id" hidden />
            }
        }

        <div class="form-group">
            <label class="col-xs-2">Название</label>
            <div class="col-xs-10">
                <input class="form-control" asp-for="model.Name" />
                <span asp-validation-for="model.Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-xs-2">Описание</label>
            <div class="col-xs-10">
                <textarea class="form-control" asp-for="model.Description"></textarea>
                <span asp-validation-for="model.Description" class="text-danger"></span>
            </div>
        </div>

        <input type="submit" class="form-control" />
    </div>
</form>

src/SchoolOfRock.Web/Views/Traning/Detail.cshtml
@model SchoolOfRock.Core.Models.Traning
@{
    Layout = "_Layout";
    ViewData["Title"] = Model.Name;
}

<h2>@ViewData["Title"]</h2>
<hr />
<div>
    <div class="row">
        <label class="col-xs-2">ID</label>
        <div class="col-xs-10">@Model.Id</div>
    </div>
    <div class="row">
        <label class="col-xs-2">Название</label>
        <div class="col-xs-10">@Model.Name</div>
    </div>
    <div class="row">
        <label class="col-xs-2">Описание</label>
        <div class="col-xs-10">@Model.Description</div>
    </div>
    <div class="row">
        <label class="col-xs-2">Занятия</label>
        <div class="col-xs-10">
            <table class="table" id="schedule-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Название курса</th>
                        <th>Дата/Время</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in Model.Schedule)
                        {

                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Date</td>
                                <td>@Model.Name</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts{

}

src/SchoolOfRock.Web/Views/Traning/Index.cshtml
@model IEnumerable<SchoolOfRock.Core.Models.Traning>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Курсы";
}

<h2>@ViewData["Title"]</h2>
<hr />
<div class="row">
    <a asp-action="CreateOrEdit" asp-route-Id="0" class="btn btn-default">Добавить занятие</a>
</div>
<hr />
<div class="row">
    <div class="col-lg-12">
        <div class="dataTables_wrapper">
            <table class="table table-striped table-bordered table-hover" id="traning-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Название</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>
                                    <a asp-action="Detail" asp-route-Id="@item.Id">Просмотреть</a> |
                                    <a asp-action="CreateOrEdit" asp-route-Id="@item.Id">Редактировать</a> |
                                    <a asp-action="ScheduleEdit" asp-route-Id="@item.Id">Настроить занятия</a> |
                                    <a asp-action="Delete" class="delete" data-post="@item.Id">Удалить</a> 
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>
<hr />
@section Scripts{
    <script src="~/lib/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
    <script>
        window.delayedFunction['set-traning-table'] = function ()
        {
            window.BrandTable = new TableObject('#traning-table');
        }
    </script>
}

src/SchoolOfRock.Web/Views/Traning/ScheduleEdit.cshtml
@model SchoolOfRock.Web.Models.ScheduleSettingModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Форма настройки занятий";
}

<h2>@ViewData["Title"]</h2>
<hr />
<form asp-action="ScheduleEdit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <table class="table" id="schedule-table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Название курса</th>
                    <th>Дата/Время</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{
                    int index = 0;
                    foreach (var item in Model.ScheduleList)
                    {

                        <tr>
                            <td>
                                <input asp-for="ScheduleList[index].Id" class="form-control" readonly/>
                            </td>
                            <td>
                                @Model.ScheduleList[index].Traning.Name
                                <input asp-for="ScheduleList[index].TraningId" hidden/>
                            </td>
                            <td>
                                <input asp-for="ScheduleList[index].Date" class="form-control" readonly />
                            </td>
                        </tr>

                        index++;
                    }
                }
            </tbody>
        </table>

        <input type="button" class="form-control" id="add-schedule-item" value="Добавить занятие"/>

        <input type="submit" class="form-control" />
    </div>
</form>

@section Scripts{
    <script>
        window.delayedFunction['set-dinamic-schedule-items'] = function ()
        {
            window.ScheduleCount = @Model.ScheduleList.Count();

            $('#add-schedule-item').click(function()
            {
                $.ajax({
                    method : "POST",
                    url : '/Traning/GetScheduleForm',
                    data : {
                        index : window.ScheduleCount,
                        traningId : @Model.TraningId,
                    },
                    success : function(html)
                    {
                        $('#schedule-table').children('tbody').append(html);
                        window.ScheduleCount++;
                    },
                    error : function(message)
                    {
                        //$('#schedule-table').children('tbody').append(html);
                        console.log(message);
                    }
                });
            });
        }
    </script>
}

src/SchoolOfRock.Web/Views/Traning/_ScheduleEditItem.cshtml
@model SchoolOfRock.Web.Models.ScheduleSettingModel
@{
    Layout = "";
    int index = ViewBag.Index;
}

<tr>
    <td>
        <input asp-for="ScheduleList[index].Id" readonly class="form-control"/>
    </td>
    <td>
        @Model.ScheduleList[index].Traning.Name
        <input asp-for="ScheduleList[index].TraningId" hidden/>
    </td>
    <td>
        <input asp-for="ScheduleList[index].Date" class="form-control" />
    </td>
</tr>